version: '3.8'

services:
  nodejs-backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  rust-backend:
    build:
      context: ./rust
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - app-network

  go-backend:
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  test-runner:
    build:
      context: ./tests
      dockerfile: Dockerfile
    volumes:
      - ./tests:/tests
      - ./results:/results
    depends_on:
      - nodejs-backend
      - rust-backend
      - go-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge