services:
  nodejs-backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  rust-backend:
    build:
      context: ./rust
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  go-backend:
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  test-runner:
    build:
      context: ./tests
      dockerfile: Dockerfile
    volumes:
      - ./tests:/tests
      - ./results:/results
    depends_on:
      - nodejs-backend
      - rust-backend
      - go-backend