[package]
name = "rust-chat-backend"
version = "0.1.0"
edition = "2021"  

[dependencies]
actix-web = "4.5.1"  
mongodb = "3.0.1"    
serde = { version = "1.0", features = ["derive"] }
bson = "2.11.0"      